version: '3.8'

services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: ${SQL_DB}
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        dist: ubi9-minimal
        jdk: 20
    image: jboss/wildfly-jdk20
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${SQL_DB}
      DB_USER: ${SQL_USER}
      DB_PASSWORD: ${SQL_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:
