version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        dist: ubi9-minimal
        jdk: 20
    image: jboss/wildfly-jdk20
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URI=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:
